base:
    logo_dir: ../assets/logos

    font: ../assets/fonts/AlibabaPuHuiTi-2-45-Light.otf
    bold_font: ../assets/fonts/AlibabaPuHuiTi-2-85-Bold.otf

    input_dir: ../factory/input
    output_dir: ../factory/output
    quality: 100

layout:
    margin:
        enable: true
        color: "#ffffff"
        size: 100

    exif_mark:
        font_size: 1
        bold_font_size: 1
        logo_position: left
        mark_position: below
        enable_dark_mode: False

    background:
        color: "#ffffff"
        use_blur_image: false
